# Generated by Django 3.1 on 2020-08-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('area', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Svgd',
            fields=[
                ('code', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('colour', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Total_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_rate', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('flood_vic_rate', models.IntegerField(default=0)),
                ('flood_vic', models.IntegerField(default=0)),
                ('crime_num_rate', models.IntegerField(default=0)),
                ('crime_num', models.IntegerField(default=0)),
                ('crime_arr', models.IntegerField(default=0)),
                ('fire_cost_rate', models.IntegerField(default=0)),
                ('fire_cost', models.IntegerField(default=0)),
                ('child_car_rate', models.IntegerField(default=0)),
                ('child_car_num', models.IntegerField(default=0)),
                ('alc_car_rate', models.IntegerField(default=0)),
                ('alc_car_num', models.IntegerField(default=0)),
                ('house_price_rate', models.IntegerField(default=0)),
                ('house_price', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(default=0)),
                ('flood_vic', models.IntegerField(default=0)),
                ('crime_num', models.IntegerField(default=0)),
                ('crime_arr', models.IntegerField(default=0)),
                ('fire_cost', models.IntegerField(default=0)),
                ('child_car_num', models.IntegerField(default=0)),
                ('alc_car_num', models.IntegerField(default=0)),
                ('house_price', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household', models.IntegerField(default=0)),
                ('total_male', models.IntegerField(default=0)),
                ('total_female', models.IntegerField(default=0)),
                ('total_total', models.IntegerField(default=0)),
                ('kor_male', models.IntegerField(default=0)),
                ('kor_female', models.IntegerField(default=0)),
                ('kor_total', models.IntegerField(default=0)),
                ('for_male', models.IntegerField(default=0)),
                ('for_female', models.IntegerField(default=0)),
                ('for_total', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Flood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField(default=0)),
                ('houses', models.IntegerField(default=0)),
                ('buildings', models.IntegerField(default=0)),
                ('public', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Fire_damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_damage', models.IntegerField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murder', models.IntegerField()),
                ('robber', models.IntegerField()),
                ('rape', models.IntegerField()),
                ('theft', models.IntegerField()),
                ('violence', models.IntegerField()),
                ('total', models.IntegerField()),
                ('arr_total', models.IntegerField()),
                ('arrest', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_num', models.IntegerField(default=0)),
                ('accident_rate', models.FloatField(default=0)),
                ('safe_num', models.IntegerField(default=0)),
                ('safe_rate', models.FloatField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident_num', models.IntegerField(default=0)),
                ('dead_num', models.IntegerField(default=0)),
                ('casual_num', models.IntegerField(default=0)),
                ('acc_rate', models.FloatField(default=0)),
                ('casual_rate', models.FloatField(default=0)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safehome.area')),
            ],
        ),
    ]
