# Generated by Django 3.0.5 on 2020-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alchohol',
            fields=[
                ('area', models.CharField(default='', max_length=30)),
                ('accident_num', models.IntegerField(default=0)),
                ('dead_num', models.IntegerField(default=0)),
                ('casual_num', models.IntegerField(default=0)),
                ('acc_rate', models.FloatField(default=0)),
                ('casual_rate', models.FloatField(default=0)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('area', models.CharField(default='', max_length=30)),
                ('accident_num', models.IntegerField(default=0)),
                ('accident_rate', models.FloatField(default=0)),
                ('safe_num', models.IntegerField(default=0)),
                ('safe_rate', models.FloatField(default=0)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('murder', models.IntegerField()),
                ('robber', models.IntegerField()),
                ('rape', models.IntegerField()),
                ('theft', models.IntegerField()),
                ('violence', models.IntegerField()),
                ('total', models.IntegerField()),
                ('arr_total', models.IntegerField()),
                ('arrest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fire_damage',
            fields=[
                ('area', models.CharField(default='', max_length=30)),
                ('fire_damage', models.IntegerField(default=0)),
                ('code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flood',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('people', models.IntegerField(default=0)),
                ('houses', models.IntegerField(default=0)),
                ('buildings', models.IntegerField(default=0)),
                ('public', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('code', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
