# Generated by Django 3.0.9 on 2020-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('household', models.IntegerField(default=0)),
                ('total_male', models.IntegerField(default=0)),
                ('total_female', models.IntegerField(default=0)),
                ('total_total', models.IntegerField(default=0)),
                ('kor_male', models.IntegerField(default=0)),
                ('kor_female', models.IntegerField(default=0)),
                ('kor_total', models.IntegerField(default=0)),
                ('for_male', models.IntegerField(default=0)),
                ('for_female', models.IntegerField(default=0)),
                ('for_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Alchohol',
            new_name='Alcohol',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='code',
            new_name='id',
        ),
    ]
