# Generated by Django 3.1 on 2020-09-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='children',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='fire_damage',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='flood',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='house',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='population',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='total',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
        migrations.AlterField(
            model_name='total_rate',
            name='region_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.region'),
        ),
    ]
