# Generated by Django 3.0.9 on 2020-08-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_rate',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('population', models.IntegerField(default=0)),
                ('flood_vic', models.IntegerField(default=0)),
                ('crime_num', models.IntegerField(default=0)),
                ('crime_arr', models.IntegerField(default=0)),
                ('fire_cost', models.IntegerField(default=0)),
                ('child_car_num', models.IntegerField(default=0)),
                ('alc_car_num', models.IntegerField(default=0)),
                ('house_price', models.IntegerField(default=0)),
            ],
        ),
    ]
