# Generated by Django 3.0.9 on 2020-08-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0002_total_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('colour', models.CharField(max_length=30)),
            ],
        ),
    ]
