# Generated by Django 3.1 on 2020-08-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0002_auto_20200826_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='areas',
        ),
    ]
