# Generated by Django 3.1 on 2020-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0003_auto_20200826_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsData',
        ),
        migrations.RenameField(
            model_name='alcohol',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='children',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='fire_damage',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='flood',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='population',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='code',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='total_rate',
            old_name='code',
            new_name='areas',
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='acc_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='casual_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='children',
            name='accident_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='children',
            name='safe_rate',
            field=models.IntegerField(default=0),
        ),
    ]
