# Generated by Django 3.1 on 2020-08-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0003_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svgd',
            fields=[
                ('id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('colour', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Colour',
        ),
    ]
