# Generated by Django 3.1 on 2020-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0004_auto_20200827_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgd',
            name='code',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
