# Generated by Django 3.1 on 2020-08-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0005_auto_20200829_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgd',
            name='colour',
            field=models.CharField(max_length=100),
        ),
    ]
