# Generated by Django 3.1 on 2020-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0006_auto_20200829_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgd',
            name='colour',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='svgd',
            name='location',
            field=models.CharField(max_length=10000),
        ),
    ]
