# Generated by Django 3.1 on 2020-08-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0007_auto_20200829_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_rate',
            name='id',
        ),
        migrations.AlterField(
            model_name='total_rate',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
    ]
