# Generated by Django 3.1 on 2020-08-31 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safehome', '0008_auto_20200831_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcohol',
            name='id',
        ),
        migrations.RemoveField(
            model_name='children',
            name='id',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fire_damage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='flood',
            name='id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='id',
        ),
        migrations.RemoveField(
            model_name='population',
            name='id',
        ),
        migrations.RemoveField(
            model_name='total',
            name='id',
        ),
        migrations.AlterField(
            model_name='alcohol',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='children',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='fire_damage',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='flood',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='house',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='population',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
        migrations.AlterField(
            model_name='total',
            name='areas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='safehome.area'),
        ),
    ]
